### ISSUE TITLE
Illustrate FullColumn Character 1 + ClothingItems

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#11]
(input for https://github.com/unfoldcollective/Insurgent-of-Myjava/issues/10)

- 1 x CharacterBody
- 1 x CharacterHead
- 9 x HeadWear
- 9 x TorsoWear
- 9 x LegsWear
- 9 x FeetWear

All layers to be illustrated at FullColumn dimensions of 480 x 1080 px.
Heads will be separate.
All ClothingItems will be illustrated the same for all Characters (and across Thumbnails).

@matopysny to define z-index order of CharacterBody, CharacterHead, HeadWear, TorsoWear, LegsWear, FeetWear (same for every character).

**Comment by bertez** [comment]
Closing to clean up milestone
