### ISSUE TITLE
Adding total of 4 WeaponItems (incl planks)

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#12]
(Input for: https://github.com/unfoldcollective/Insurgent-of-Myjava/issues/9)

4 WeaponItems at FullRes and Thumbnail size
- 1 knife
- 1 axe
- 2 planks

- [ ] @matopysny to prepare illustrations
- [ ] @bertez to incorporate image in app

**Comment by matopysny** [comment]
please find weapons thumbnails here:
https://drive.google.com/open?id=1PIzi7ruDIao_WcKa7FkA_BKecWhGwvmu
