### ISSUE TITLE
Style landing page

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#18]
(Input to: https://github.com/unfoldcollective/Insurgent-of-Myjava/issues/17)

**Comment by phivk** [comment]
@matopysny can you please prepare:
- landing background image
- SVG version of button outline
?

**Comment by bertez** [comment]
@matopysny when you have a minute could you share the baackground image you used on the frontpage? Thanks!

Forget the button for the time being, I'm still finding the best solution for those scooped borders

**Comment by phivk** [comment]
@bertez I solved the fancy button borders in CSS for the other project for the same exhibition:
https://github.com/SlovakNationalGallery/cyoa1848/blob/147b00b16370a95ee754143523c13f8579bb3608/css/cyoa48.css#L829-L836

 ![screen shot 2019-02-04 at 21 46 33](https://user-images.githubusercontent.com/902958/52236237-90d49f80-28c6-11e9-8d49-136939884994.png)

perhaps it's helpful...

see also:
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-image_generator

**Comment by matopysny** [comment]
Landing page background @bertez 
https://drive.google.com/open?id=18PkTmaHRgAwiI4mfm1Bq-fMAbHHJzCEM
