### ISSUE TITLE
create loading animation for step 8

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#19]
![insrg-layout-1-3-loading animation](https://user-images.githubusercontent.com/902958/52415485-5eee5380-2ae7-11e9-9a9e-f447cd6f2f7b.jpg)

Animation:

1. fadeIn central image
2. circle of knives appearing one by one
3. fadeOut all

- [ ] @matopysny: prepare SVG with all elements
- [ ] @bertez: animate knives appearing **one by one** in clockwise direction

**Comment by matopysny** [comment]
@bertez @phivk please find svg with separate layers here:
https://drive.google.com/open?id=1go_RMf03TS0TKU9a5IHbxLQREwIyjAiJ

**Comment by bertez** [comment]
We'll need a gif for the knives animation as we spoke on the slack channel @matopysny

**Comment by bertez** [comment]
Please reasign this issue to me when the gif is available. :+1:

**Comment by matopysny** [comment]
@bertez @phivk please find animated gif here:
https://drive.google.com/open?id=1go_RMf03TS0TKU9a5IHbxLQREwIyjAiJ

**Comment by phivk** [comment]
this folder: https://drive.google.com/drive/folders/1mtbiuE1V2kuoG1u8ElDZIS4d7S31diXz
has this GIF: https://drive.google.com/open?id=18YsrrhF0dRa9_VYKcDQwDMJkqR_ksQDj

The GIF has the hat and axes in the middle. 
@bertez is this the way you need it?
