### ISSUE TITLE
Step 4b: CharacterCustomisation UI

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#2]
![190128 4b charactercustomisation ui](https://user-images.githubusercontent.com/902958/51829058-1ff11e80-22ed-11e9-9a3c-e5a97891a26c.png)

Step 4b `CharacterCustomisation UI` let's the user dress the selected `Character`.

**Comment by bertez** [comment]
Guide for defining the clothing parts boxes/overlays:
![overlays](https://user-images.githubusercontent.com/159838/51829575-216f1680-22ee-11e9-9b85-e3aa46e7e473.png)

**Comment by bertez** [comment]
Guide for defining clothing parts dropzones/overlays:

![overlays](https://user-images.githubusercontent.com/159838/51829675-5c714a00-22ee-11e9-8d5a-65aabb2652ee.png)

**Comment by phivk** [comment]
Considering size of the `ClothingItems` is the same size as the `ClothingItemOverlays`, it sounds like we would use `distanceTop` and `distanceBottom` not only for the `ClothingItemOverlays` but also for positioning the `ClothingItems` themselves. Right?

**Comment by bertez** [comment]
![text2754](https://user-images.githubusercontent.com/159838/51830618-875c9d80-22f0-11e9-934d-bbeff9ff8798.png)

like this

**Comment by bertez** [comment]
Maybe for a different character the actual helmet position on the image area will be different to match the character head position... that way we can be more flexible with the character body positions

**Comment by phivk** [comment]
considering we already discussed having different `ClothingItemSizes` for 'LegWear' and 'TorsoWear' `ClothingItems`, this should give us further flexibility for boy positions 🙂

**Comment by matopysny** [comment]
[Insurgent-Y-Axis.pdf](https://github.com/unfoldcollective/Insurgent-of-Myjava/files/2803037/Insurgent-Y-Axis.pdf)
Do I understand it right? @bertez

**Comment by bertez** [comment]
@matopysny yes, perfect! thanks

**Comment by matopysny** [comment]
So "image" means whole character (for instance h: 810 px). Not Height of the screen right?

**Comment by matopysny** [comment]
So clothing items will be place in a some layer order (in terms of altitude) from the Bottom "Layer 1" to Top "layer 5" @bertez ?

[Insurgent-Y-Axis-2.pdf](https://github.com/unfoldcollective/Insurgent-of-Myjava/files/2803177/Insurgent-Y-Axis-2.pdf)

**Comment by bertez** [comment]
> So "image" means whole character (for instance h: 810 px). Not Height of the screen right?

yes, the image size

**Comment by bertez** [comment]
> So clothing items will be place in a some layer order (in terms of altitude) from the Bottom "Layer 1" to Top "layer 5" @bertez ?
> 
> [Insurgent-Y-Axis-2.pdf](https://github.com/unfoldcollective/Insurgent-of-Myjava/files/2803177/Insurgent-Y-Axis-2.pdf)

yes

**Comment by bertez** [comment]
# Important change!!
The distanceBottom value is not the distance from the top to the bottom side of the overlay box... is the height of the overlay box. See sketch:
![overlays](https://user-images.githubusercontent.com/159838/51846703-61e48980-231a-11e9-911d-e3f10a702ade.png)

my mistake, sorry

**Comment by phivk** [comment]
OK, in that case let's call the 2 properties:
- `OverlayTop`
- `OverlayHeight`

so for each character, we will have:

1. 
  - `HeadOverlayTop`
  - `HeadOverlayHeight`
2.
  - `TorsoOverlayTop`
  - `TorsoOverlayHeight`
3.
  - `LegsOverlayTop`
  - `LegsOverlayHeight`
4.
  - `FeetOverlayTop`
  - `FeetOverlayHeight`

@bertez 👌 ?

**Comment by bertez** [comment]
yes, you can see those values already in the yml

https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/data/content.yml#L35

**Comment by bertez** [comment]
well the names are not the same because I tried to keep them short because this file actually transfer between the server and the client

**Comment by matopysny** [comment]
@bertez @phivk please find 3 colors clothing set for Thin Character here: https://drive.google.com/open?id=16spYP2tvSb3oIkdjpN-9m8GqnxmlSt2A

**Comment by bertez** [comment]
Thanks for the set @matopysny 

I haven't downloaded until now and as you see in slack I'm still using development placeholders, but tomorrow I'll start using your files. By the way, great illustrations, I love them.

Maybe tomorrow morning we can have a small meeting in slack, via text chat is enough to talk about filename conventions.

Just a quick question. Why is the head of the character in a separate file?

Thanks!

**Comment by matopysny** [comment]
Hi @bertez @phivk , please find measurements in "%" OverlayHeights (Hopely didn't mess up naming) and Y positions in attached PDF:
[ch-1-mesurements.pdf](https://github.com/unfoldcollective/Insurgent-of-Myjava/files/2809882/ch-1-mesurements.pdf)

**Comment by matopysny** [comment]
@bertez Actually, I was thinking: Can we make every clothing item exported as SVG 480px x 1080px, but graphics would be in particular X and Y position? This way we could avoid percentage and positioning on Y axis. Everything would be "dropped" at the same place. Or we can't do that because of highlighting while dropping?

**Comment by matopysny** [comment]
Thanks, Berto, I appreciate it.

**Comment by phivk** [comment]
Given the difficulties of aligning the ClothingItems to the Character, I think we should go with @matopysny 's suggestion:

> @bertez Actually, I was thinking: Can we make every clothing item exported as SVG 480px x 1080px, but graphics would be in particular X and Y position? This way we could avoid percentage and positioning on Y axis. Everything would be "dropped" at the same place. Or we can't do that because of highlighting while dropping?

That way pixel perfect alignment of ClothingItems is handled by graphics (prepared by Mato),
generic average positioning of highlight areas is dealt with in code (same for each character)

**Comment by bertez** [comment]
Closing this
