### ISSUE TITLE
CSS: implement final design

### ISSUE THREAD

**Issue by bertez** [unfoldcollective/Insurgent-of-Myjava#31]
- [x] Add unfold tagline to the homepage
- [x] Replace iconbuttons with images
- [x] Replace clothingitems tabs with images
- [x] Replace trash dropzone with icon
- [x] Create circle timeout button
- [x] Create resettable timeout button for the gallery
- [ ] Add skip button to the input email step
- [ ] Better Cta button outlines
- [x] Add weapon name to the sidebar
- [x] Add title to the contexts steps
- [x] Add character name to the sidebar

**Comment by phivk** [comment]
final design 'INSRG-Layout-1-4.pdf':
https://drive.google.com/drive/folders/1Om4Qm2gR9l4UvsYT9t478Jp7SNq9K9i2

**Comment by phivk** [comment]
also:

- [ ] Step 1: replace landing bg with high res image
- [ ] create button outlines
- [ ] change LanguageSwitch order: first SK, them EN
- [ ] fix top-alignment of LanguageSwitch

<img width="77" alt="screenshot 2019-02-20 at 11 18 05" src="https://user-images.githubusercontent.com/902958/53084529-4f1c3980-3501-11e9-8a4a-2139c673df47.png">

- [ ] exchange SidebarTitle and SidebarText to be static per Step (not dynamically related to Characters or BaseWeapons)
- [ ] make dimensions of ClothingItems consistent

<img width="300" alt="screenshot 2019-02-20 at 11 21 27" src="https://user-images.githubusercontent.com/902958/53084731-b9cd7500-3501-11e9-8c1c-a43eecc5b4df.png">

- [ ] Make size and positioning of WeaponItems consistent

<img width="301" alt="screenshot 2019-02-20 at 11 22 32" src="https://user-images.githubusercontent.com/902958/53084812-e3869c00-3501-11e9-9b56-65babc7e2f4f.png">

- [ ] Step 7: replace IconTrash with image
- [ ] Step 7: style Finish button as Button with outline

<img width="82" alt="screenshot 2019-02-20 at 11 24 35" src="https://user-images.githubusercontent.com/902958/53084927-1df03900-3502-11e9-8455-f5f0908f87c8.png">

- [ ] Step 10b: add skip button to bottom right
- [ ] Step 11: Make LeaveGallery button into TimeoutButton
- [ ] Step 11: Make BackToGallery button into TimeoutButton

**Comment by bertez** [comment]
Checking the repeated items

**Comment by bertez** [comment]
@phivk I've moved some of your sub-issues to the main issue the other ones are closed

**Comment by bertez** [comment]
Closing this in favor of the issues of the preproduction milestone
