### ISSUE TITLE
Canvas: implement flashing messages

### ISSUE THREAD

**Issue by bertez** [unfoldcollective/Insurgent-of-Myjava#34]

**Comment by bertez** [comment]
Hi @matopysny and @phivk , I'm adding you both to discuss the flashing messages... my main question is:

- which user events trigger a flashing message?

**Comment by phivk** [comment]
we should support all of the following:

- Characters
- ClothingItems
- BaseWeapons
- WeaponItems

**Comment by bertez** [comment]
The easiest is fun facts per category
But I can code a combination of category based facts and item facts... if the item does not have any fact I can pick a random category fact if exists...

**Comment by bertez** [comment]
after a more detailed analysis maybe it is better to leave this issue frozen until knowing better the final texts

**Comment by phivk** [comment]
Update: FunFactTexts will NOT be specific to any content item. They are simply associated to one of the 4 content steps:
		
- 3. CharacterSelection	
- 4. CharacterCustomisation	
- 6. BaseWeaponSelection	
- 7. WeaponComposition

@bertez I'm not sure when/how to best trigger random FunFactCards per category. Options I see:

1. On first interaction with content
2. After a timeout

**Comment by bertez** [comment]
Good news! I'll work on this issue tomorrow and get back to you!

**Comment by phivk** [comment]
Text writing and translation is now complete:
https://docs.google.com/spreadsheets/d/1xcpT2AaqGGpXQtfO6zpJr3-XoFLjC9NaCsCZjLwVrkM/edit#gid=0

**Comment by bertez** [comment]
Fun fact addes, please complete the yaml with the rest of the content.

**Comment by phivk** [comment]
content completed
