### ISSUE TITLE
Step 10b: Implement email template

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#36]
Both locales will use the same bilingual email template: SK text first, followed by EN text.
(SK will be translated shortly, along with other strings).

---

[SK Text to follow]

Fellow revolutionary,

Congratulations on your recent accomplishment! Thanks to your efforts we shall enter the battle fashionably and well equipped!

Your insurgent, {{insurgent.name}}, is ready for battle:
{{insurgent.url}}

The Insurgent of Myjava application is brought to you by [Unfold Collective](http://unfold.is/) in collaboration with [lab.SNG](http://lab.sng.sk/).

---

**Comment by phivk** [comment]
> if we send a link to the gallery, the app will be public, so I think is better to send the image attached and never link publicly the application

@bertez good point. Still, I'd much rather send links than images.
would there be a simple way to:
- allow users to access their insurgents & the full gallery publically
- restrict access to the creation steps

we could have a simple login step for the main routes that are used on the touchscreen, and separate public routes to give access to created Insurgents... 🤔?

**Comment by bertez** [comment]
At this point of the project and without previous planning integrating a login step is very complex... let me think of an alternative.

**Comment by phivk** [comment]
What I had in mind was a simple htpasswd type of solution... Doesn't have to be client friendly...

Alternatively we might solve the issue by exposing the public gallery via another URL. Again, I'm not sure if that is straightforward at all...

Just exploring options here... In the end we should go with the simplest.
