### ISSUE TITLE
Step 3: Integrate final Character Illustrations

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#38]
final Character Illustrations here:
https://drive.google.com/drive/folders/1j91407KWuV2O1pXKTCe9mSbQmOmlRERl?usp=sharing

**Comment by bertez** [comment]
Mato, I'll need a complete version of each character... Included head and body, named:
- character-0-full.svg
- character-1-full.svg
- character-2-full.svg

remember we use 0-index numbering
