### ISSUE TITLE
add fade in to page transitions and UI elements

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#42]
Goal is to make the experience feel smooth.

Page transitions can be a simple 'dip to black'

Graphical UI element that appear on screen such as:
- keyboard
- ClothingItems & WeaponItems
- Carousel content

also figures (in basic underwear state as well as final dressed state) appear in staggered abrupt (non-smooth) way after a new pageload (e.g. between steps 3 & 4, 11a & 11b)
@bertez Not sure if this should be addressed as part of this issue or whether it has a separate solution?

Perhaps also preloading images helps?

**Comment by bertez** [comment]
All the images are preloaded at those steps... I'll try to find a way to create a fading transition between pages that should create a smoother experience and maybe fix somehow this issue... but there are a lot of things that can break this smooth transitions like network latency, cpu power of the machine thats running the app, etc...

**Comment by bertez** [comment]
I've added transitions to everything but the keyboard, which need a deep refactoring of some complex parts of the process and will block me during hours, please let me know if the keyboard can appear without transition... if not I'll need more time (hours) to rebuild some other parts of the app.
