### ISSUE TITLE
improve WeaponItems content & layout in Sidebar

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#43]
current version:
<img width="304" alt="screenshot 2019-02-20 at 15 35 36" src="https://user-images.githubusercontent.com/902958/53099165-8270bf80-3525-11e9-8051-3766b3817537.png">

some issues with current version:
- all items are very straight. perhaps we can try rotating each WeaponItem?
- layout uses 6 rows x 4 columns == 24 slots, we should fill all slots
- the ordering seems chaotic and random. could this be improved? 🤔

we should include:
- this separate metal part (client wants it):
<img width="235" alt="screenshot 2019-02-20 at 15 39 18" src="https://user-images.githubusercontent.com/902958/53099274-c06de380-3525-11e9-9d1f-3eaca9767a15.png">

- wooden planks. perhaps 2 different dimensions are enough?

@matopysny can you add links to the above items in a comment to this issue?

@matopysny can you propose a slight redesign to address issues above?

**Comment by matopysny** [comment]
- So there should be 2 more objects. Planks were meant to be there.

- rotating weapon items for the thumbnails: sure I think it will work. Should I export new thumbnails with an (ca 10°) angle or you can do it by code somehow? @bertez 

- client wants a metal part of scythe as a separate weapon item available in the sidebar pallet right?: Should we substitute one of them by this scythe? @phivk 

-  Planks: As long as we have rotate, scale... functionality I would go with 2 plans: A-square, B-one dimension longer rectangle. There is also chain available for chaining things together

**Comment by bertez** [comment]
@matopysny I can do the rotation, no problem!

**Comment by matopysny** [comment]
Great thanks @bertez

**Comment by phivk** [comment]
> So there should be 2 more objects. Planks were meant to be there.

👌 correct

> client wants a metal part of scythe as a separate weapon item available in the sidebar pallet right?: Should we substitute one of them by this scythe? @phivk

yes, let's substitute this item:

<img width="56" alt="screenshot 2019-02-22 at 15 35 18" src="https://user-images.githubusercontent.com/902958/53249268-fd69df80-36b7-11e9-8ce9-d9d86fef6de1.png">

> Planks: As long as we have rotate, scale... functionality I would go with 2 plans: A-square, B-one dimension longer rectangle. There is also chain available for chaining things together

I don't think square plank is very 'versatile'. I would go for:
- A: 2:1 length:width ratio
- B: 4:1 length:width ratio

@matopysny OK?

@bertez @matopysny can we do something to make the *item size* in the thumbnails more consistent? currently there is a big contrast in size, e.g. between knife and axe...
Perhaps the knife can be vertical to be less constrained by width?
Perhaps the easiest way to go would be for Mato to create a set of thumbnails that are optimized for consistency?

**Comment by bertez** [comment]
The images on the sidebar **must** be the same that the ones dragged and dropped on the canvas. The app works cloning them so there cannot be support of thumbnails different than the actual image that's dragged and dropped. Of course it could be if it was planned before, but at this point changing that behaviour implies a lot of changes in the app.

In my opinion there is nothing wrong with the current version... the sidebar is a drawer of multiple tools of different shapes and sizes, which is what the user sees. But if you want to make a drawer more visually balanced we have to work with rotation or slight size changes inside the current bounds of each image box.

**Comment by phivk** [comment]
thanks for clarifying. we are **ONLY using easy solutions for cosmetic adjustments like this**.

so perhaps the thumbnails can be styled more consistent by having a `max-height` set in CSS?

**Comment by phivk** [comment]
Planks and Scythe in this folder
https://drive.google.com/drive/folders/1mtbiuE1V2kuoG1u8ElDZIS4d7S31diXz

**Comment by phivk** [comment]
closed via 153b28616
