### ISSUE TITLE
decrease (or communicate) loading time between Signing and Gallery steps

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#44]
Currently transition between steps 10. Signing and 11. Gallery take long.

@bertez Can this time be decrease by starting to save compositions earlier and only updating Name and Email?

**Comment by bertez** [comment]
The compositions are actually saved early, that steps takes longer because it takes some time to create an screenshot of the composition and generate the thumbnails... this process must be done at some point so it will be better to show an "working on it" indicator

**Comment by phivk** [comment]
I see 2 options:
1. show a "working on it" indicator
2. generate the thumbnails while user is typing name and email (or already during `Step 9. Result`), if generating can be done in an a-sync, non-blocking way...

I find option 2. more elegant, but if it is time-consuming to implement I'm ok to go with option 1.
