### ISSUE TITLE
Use randomly selected background from set of 3 different background for resulting composition

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#46]
The aim is to facilitate variety in the Gallery overview.
After user finishes `Step 7. WeaponComposition`, one of 3 backgrounds is randomly chosen for the resulting composition.

- [x] @matopysny to prepare 2 more backgrounds (so we have 3 in total)
- [x] @bertez to support random selection of background

@matopysny I have prepared [a collection of paintings](https://www.are.na/philo-van-kemenade/1848-landscapes) that are:
- Public Domain, so free to download at high res
- 19th century
- oil paintings
- in landscape motif without people
- mostly in landscape orientation (or have large width)

**Comment by phivk** [comment]
@bertez Mato will deliver additional 2 final backgrounds by Monday 13.00.
Please use the existing background as a placeholder, so you don't have to wait for content.

**Comment by phivk** [comment]
backgrounds by Mato:

https://drive.google.com/drive/folders/1F9sCZ1GgMutNsEhBM70ijQqcVRsIZmH7?usp=sharing
https://drive.google.com/open?id=1Szbpeyh24UkQZ0_obqGzPyZk_vHHDfKb

**Comment by bertez** [comment]
https://github.com/unfoldcollective/Insurgent-of-Myjava/issues/47

**Comment by phivk** [comment]
closing in favour of #47
