### ISSUE TITLE
Replace new creation background images placeholders

### ISSUE THREAD

**Issue by bertez** [unfoldcollective/Insurgent-of-Myjava#47]
https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/app/static/bg2.jpg
https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/app/static/bg3.jpg

When the user is finishing the creation a random background is chosen between bg1.jpg, bg2.jpg and bg3.jpg. 

Replace bg2.jpg and bg3.jpg with the right backgrounds.

You can add more backgrounds putting the in the `app/static` directory and adding them to the content.yml:

https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/app/data/content.yml#L223

**Comment by phivk** [comment]
closed via ec9d5ee
