### ISSUE TITLE
Sending email

### ISSUE THREAD

**Issue by bertez** [unfoldcollective/Insurgent-of-Myjava#48]
The app needs to have an Gmail address configured to send email:

- register a gmail address
- allow less secure apps to send email (https://myaccount.google.com/lesssecureapps?pli=1)
- when the app is in production create an `.env` file in the rooth with the credentials (see `.env.example`)

Please check the gmail sending limits: https://support.google.com/a/answer/166852?hl=en and provide a different email server if the limits are not enough.

**Comment by phivk** [comment]
set up
