### ISSUE TITLE
Create a "Working on it" overlay

### ISSUE THREAD

**Issue by bertez** [unfoldcollective/Insurgent-of-Myjava#49]
that overlays appears briefly at the end of 7b and during a couple of seconds at the end of 10b

**Comment by bertez** [comment]
Create = Design

**Comment by phivk** [comment]
can we use the existing loading gif?

**Comment by bertez** [comment]
If we dont mind that the gif loops a couple of times or dissapear before ending no problem (we cannot control the duration of this saving steps)

**Comment by bertez** [comment]
In fact, the gif does not loop at all, we'll need a looping gif

**Comment by phivk** [comment]
@matopysny can you make the existing loading gif looping?

**Comment by phivk** [comment]
looping gif:
https://drive.google.com/open?id=1zOCLqCjjcrZaMrSSiZat1J-Gq9Fhfa6d

**Comment by bertez** [comment]
Thanks @phivk I'll modify the component and behaviour later today, the change is not hard but neither is trivial...
