### ISSUE TITLE
Mysterious 'broken image' icons appeared when dropping plate onto canvas

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#71]
Only managed to achieve this bug once, not replicated yet...

![IMG_20190311_162619](https://user-images.githubusercontent.com/902958/54158779-997f3f00-444b-11e9-8c89-138f59302c79.jpg)

**Comment by bertez** [comment]
Tried hard but cannot reproduce, probably a cache/network issue, please open again if you notice it again...

**Comment by bertez** [comment]
![image](https://user-images.githubusercontent.com/159838/54527146-480a0f00-4979-11e9-9bd0-0ea48eb3a08d.png)
