### ISSUE TITLE
Increase size of Nail & Chain WeaponItems

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#72]
current default size is too small and makes it hard to rotate and scale with 2 fingers.

@bertez should this be done by editing "width and height in the <svg> tag, editing the file by hand"?
If so, I will take care of this.

![IMG_20190311_162248](https://user-images.githubusercontent.com/902958/54159436-43130000-444d-11e9-8940-404f3d27c6ab.jpg)

**Comment by bertez** [comment]
It's more safe to change the drawing size on the editor @matopysny used and export them again... remember that you should include manually the width and height attributes on the `<svg>` element.

**Comment by phivk** [comment]
closed via #b22d380f
