### ISSUE TITLE
relative size of ClothingItemThumbnails in SideBar is unequal

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#73]
Relative size of ClothingItemThumbnails should be equal, e.g. the size of the slots for the head / hips should be equally wide in the examples below.

![insurgent-ClothingItems unequal size-legwear](https://user-images.githubusercontent.com/902958/54577090-b7065880-49b7-11e9-85d7-7c062b768af9.png)
![insurgent-ClothingItems unequal size-headwear](https://user-images.githubusercontent.com/902958/54577092-b7065880-49b7-11e9-9c9a-bc152ef6f7b7.png)

**Comment by bertez** [comment]
Hi philo, this is a design issue, @matopysny should balance the items sizes and export again the images, in this case you **don't need** to manually set the width and height of the svg files.

**Comment by phivk** [comment]
@matopysny can you do a new export of the ClothingItems to make sure they are equally sized?

**Comment by phivk** [comment]
updated ClothingItemThumbnails by @matopysny:
https://drive.google.com/drive/folders/13Es7SZbGhnAMXdtwbMXRUMJMYXCIH3y8?usp=sharing
