### ISSUE TITLE
move loading animation between WeaponComposition and Result steps

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#76]
it should be here:
<img width="585" alt="Screenshot 2019-03-22 at 13 02 34" src="https://user-images.githubusercontent.com/902958/54821562-dbf21880-4ca2-11e9-8a62-0e4e5d660497.png">

not after submitting the name / email (gallery can be load instantaneously right?)

**Comment by bertez** [comment]
Added a 3 seconds timeout between Canvas and Finish. The Submitting to gallery also has a timeout that cannot be reduced much because of some processes that cannot be async.
