### ISSUE TITLE
timeout duration of 1st context step is too long

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#79]
<img width="1792" alt="Screenshot 2019-03-22 at 13 43 51" src="https://user-images.githubusercontent.com/902958/54823568-8caee680-4ca8-11e9-9390-d8f12d5f6c2a.png">

I tried decreasing it here, but it still seems to be around 20 seconds:
https://github.com/unfoldcollective/Insurgent-of-Myjava/commit/a12aea5622cce9526d5636e1d2ac5d78d7b3bfea

**Comment by bertez** [comment]
It works for me, maybe it was a cache issue? Now is 10 seconds.
