### ISSUE TITLE
Step 7: WeaponCustomisation UI

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#9]
UI Design including ComponentNaming:
https://zpl.io/VOKzNdj

**Comment by phivk** [comment]
in Apprentice, we had 5 * 8 == 40 objects in the Sidebar.
@matopysny's latest design includes 3 * 4 == 12 WeaponItems.
I think it would be nice to have more than 12, if we can manage the time needed for illustration.
I was thinking 4 * 6 == 24 would give a nice layout.

@matopysny do you think that is a realistic number in terms of both layout and time needed for illustration?

**Comment by phivk** [comment]
Latest graphic design for reference:
![7b weaponcomposition](https://user-images.githubusercontent.com/902958/52164394-fa9b5080-26f0-11e9-9f1a-9c20cb12c526.jpg)

**Comment by bertez** [comment]
Closing
